"""Post-processing business logic for extracted transmission elements.

This module contains deterministic Python logic that MUST be applied
after the LLM extraction. These rules ensure data consistency that
the LLM cannot guarantee:

1. Element Code  - Unique, deterministically generated by code
2. Inter/Intra   - Normalised from the scheme name
3. Status        - Guaranteed by doc_type (not LLM guess)
4. Source        - Set programmatically from doc_type
5. MVA           - Parsed reliably from transmission_scope text
6. Parent-child  - Scheme name inherited by child elements
"""

from __future__ import annotations

import hashlib
import re
from typing import Optional

from app.schemas import DocType, TransmissionElement


# ── 1. Element Code Generation ─────────────────────────────────────────


def generate_element_code(
    element: TransmissionElement,
    index: int,
    doc_type: DocType,
) -> str:
    """Generate a unique, deterministic element code.

    Strategy:
    - If the LLM already extracted a valid EL-XXXXX code, keep it.
    - Otherwise, generate one from a hash of (scheme + scope + index)
      to ensure uniqueness and repeatability across runs.

    Args:
        element: The extracted element.
        index: Sequential index within the document (1-based).
        doc_type: Document type for prefix disambiguation.

    Returns:
        Element code string like ``EL-TBCB-00042`` or ``EL-RTM-00015``.
    """
    existing = (element.element_code or "").strip()

    # Keep valid existing codes
    if existing and re.match(r"^EL-[A-Z0-9]{3,6}$", existing):
        return existing

    # Generate deterministic code from content hash
    prefix_map = {
        DocType.TBCB_UC_REPORT: "TBUC",
        DocType.TBCB_COMM_REPORT: "TBCM",
        DocType.RTM_UC_REPORT: "RTM",
    }
    prefix = prefix_map.get(doc_type, "GEN")

    # Create a short hash from scheme+scope for determinism
    content = f"{element.transmission_scheme}|{element.transmission_scope}|{index}"
    short_hash = hashlib.md5(content.encode()).hexdigest()[:4].upper()

    return f"EL-{prefix}-{index:04d}-{short_hash}"


# ── 2. Inter/Intra Tx Element (State/Region Name) ─────────────────────

# Common Indian state abbreviations and full names found in reports
_STATE_PATTERNS = [
    # States commonly found in transmission scheme names
    (r"\bRajasthan\b", "Rajasthan"),
    (r"\bGujarat\b", "Gujarat"),
    (r"\bKarnataka\b", "Karnataka"),
    (r"\bAndhra\s*Pradesh\b", "Andhra Pradesh"),
    (r"\bTelangana\b", "Telangana"),
    (r"\bTamil\s*Nadu\b", "Tamil Nadu"),
    (r"\bMaharashtra\b", "Maharashtra"),
    (r"\bMadhya\s*Pradesh\b", "Madhya Pradesh"),
    (r"\bUttar\s*Pradesh\b", "Uttar Pradesh"),
    (r"\bHaryana\b", "Haryana"),
    (r"\bPunjab\b", "Punjab"),
    (r"\bKerala\b", "Kerala"),
    (r"\bJammu\s*(?:&|and)\s*Kashmir\b", "Jammu & Kashmir"),
    (r"\bChhattisgarh\b", "Chhattisgarh"),
    (r"\bWest\s*Bengal\b", "West Bengal"),
    (r"\bOdisha\b", "Odisha"),
    (r"\bJharkhand\b", "Jharkhand"),
    (r"\bBihar\b", "Bihar"),
    (r"\bAssam\b", "Assam"),
    (r"\bArunachal\s*Pradesh\b", "Arunachal Pradesh"),
    (r"\bMizoram\b", "Mizoram"),
    (r"\bMeghalaya\b", "Meghalaya"),
    (r"\bDelhi\b", "Delhi"),
    (r"\bGoa\b", "Goa"),
    (r"\bDD\s*(?:&|and)\s*DNH\b", "DD & DNH"),
    (r"\bLeh\b", "Leh"),
    (r"\bLadakh\b", "Ladakh"),
    # Regional identifiers from RTM reports
    (r"\bWRES\b", "Western Region"),
    (r"\bERES\b", "Eastern Region"),
    (r"\bNERES\b", "North Eastern Region"),
    (r"\bNRES\b", "Northern Region"),
    (r"\bSRES\b", "Southern Region"),
    # Khavda / REZ identifiers
    (r"\bKhavda\b", "Gujarat (Khavda)"),
]


def extract_state_name(scheme_name: str, scope_name: str = "") -> str:
    """Extract the state/region name from the transmission scheme or scope.

    For TBCB reports, the inter/intra element is typically the state
    where the project is located. This function reliably extracts it
    from the scheme name text.

    Args:
        scheme_name: Full transmission scheme name.
        scope_name: Transmission scope (fallback search).

    Returns:
        State name string, or empty string if not found.
    """
    combined = f"{scheme_name} {scope_name}"

    for pattern, state in _STATE_PATTERNS:
        if re.search(pattern, combined, re.IGNORECASE):
            return state

    return ""


# ── 3. Status — Determined by Document Type ────────────────────────────


def get_status_for_doc_type(doc_type: DocType) -> str:
    """Return the correct status string based on document type.

    Business Rule:
    - TBCB_UC_Report  -> "Under Construction"
    - RTM_UC_Report   -> "Under Construction"
    - TBCB_Comm_Report -> "Commissioned"
    """
    if doc_type in (DocType.TBCB_UC_REPORT, DocType.RTM_UC_REPORT):
        return "Under Construction"
    elif doc_type == DocType.TBCB_COMM_REPORT:
        return "Commissioned"
    return "Unknown"


# ── 4. Source — Set from Document Type ─────────────────────────────────


def get_source_for_doc_type(doc_type: DocType) -> str:
    """Return the canonical source identifier for a document type."""
    return doc_type.value


# ── 5. MVA Parsing from Scope Text ─────────────────────────────────────

# Regex patterns for MVA extraction from scope strings
# Matches: "2x1500MVA", "3x1500 MVA", "1500MVA", "1500 MVA",
#           "2x500MVA", "500MVA", "3x200 MVA", etc.
# Excludes: "MVAr" (reactive power, not transformation capacity)
_MVA_PATTERN = re.compile(
    r"(\d+)\s*[xX×]\s*(\d+)\s*MVA(?!r)",
    re.IGNORECASE,
)
_MVA_SINGLE = re.compile(
    r"(\d+)\s*MVA(?!r)",
    re.IGNORECASE,
)


def parse_mva_from_text(text: str) -> Optional[float]:
    """Parse MVA capacity from a transmission scope or scheme string.

    Examples:
        "2x1500MVA, 765/400KV"     -> 3000.0
        "3x500 MVA, 400/220 kV"    -> 1500.0
        "1500 MVA"                 -> 1500.0
        "1x1500 MVA ICT"           -> 1500.0
        "No MVA info here"         -> None
        "2x500 MVA ... 3x1500 MVA" -> 5500.0 (sum all)
    """
    if not text:
        return None

    total_mva = 0.0

    # First find all NxM MVA patterns
    multiplied = _MVA_PATTERN.findall(text)
    if multiplied:
        for count_str, mva_str in multiplied:
            total_mva += int(count_str) * int(mva_str)
        return total_mva

    # Fallback: single MVA value
    single = _MVA_SINGLE.findall(text)
    if single:
        # Take the largest MVA value found (likely the main capacity)
        values = [int(v) for v in single]
        return float(max(values))

    return None


# ── 6. Parent-Child Scheme Inheritance ─────────────────────────────────


def inherit_scheme_to_children(
    elements: list[TransmissionElement],
) -> list[TransmissionElement]:
    """Propagate parent scheme name to child elements.

    In the source PDFs, the transmission scheme name appears only on
    the first row (the "parent" / project header row). Subsequent rows
    (children) under that scheme have an empty scheme field.

    This function fills in the scheme name for all children by looking
    at the previous element with a non-empty scheme.

    Also inherits: executing agency, SPV transfer date, cost,
    original/anticipated SCOD from parent when children have empty values.
    """
    current_scheme = ""
    current_inter_intra = ""
    current_awarded_to = ""
    current_spv_date = ""

    for elem in elements:
        # Detect parent rows: they have a scheme name
        if elem.transmission_scheme and elem.transmission_scheme.strip():
            current_scheme = elem.transmission_scheme.strip()
            if elem.inter_intra_tx_element:
                current_inter_intra = elem.inter_intra_tx_element
            if elem.awarded_to:
                current_awarded_to = elem.awarded_to
            if elem.spv_transfer_date:
                current_spv_date = elem.spv_transfer_date
        else:
            # Child row: inherit from parent
            if current_scheme:
                elem.transmission_scheme = current_scheme
            if not elem.inter_intra_tx_element and current_inter_intra:
                elem.inter_intra_tx_element = current_inter_intra
            if not elem.awarded_to and current_awarded_to:
                elem.awarded_to = current_awarded_to
            if not elem.spv_transfer_date and current_spv_date:
                elem.spv_transfer_date = current_spv_date

    return elements


# ── 7. Percentage Normalisation ────────────────────────────────────────


def normalise_percentages(element: TransmissionElement) -> TransmissionElement:
    """Normalise percentage fields to 0.0-1.0 scale.

    The LLM may return percentages as:
    - Already normalised: 0.83, 1.0
    - As whole percentages: 83, 100, 92
    - As percentage strings that were parsed to float: 83.0, 100.0

    Rule: If the value is > 1.0, divide by 100.
    """
    # Transmission line progress
    if element.phys_progress_tx_line:
        prog = element.phys_progress_tx_line
        for field in ("foundation_pct", "erection_pct", "stringing_pct"):
            val = getattr(prog, field)
            if val is not None and val > 1.0:
                setattr(prog, field, val / 100.0)

    # Substation progress
    if element.phys_progress_substation:
        prog = element.phys_progress_substation
        for field in ("civil_work_pct", "equipment_received_pct", "equipment_erected_pct"):
            val = getattr(prog, field)
            if val is not None and val > 1.0:
                setattr(prog, field, val / 100.0)

    return element


# ── 8. MVA Backfill from Scope ─────────────────────────────────────────


def backfill_mva(element: TransmissionElement) -> TransmissionElement:
    """If MVA is missing, try to parse it from the transmission_scope text.

    This is the business rule: MVA is directly extracted/computed from
    the Scope column when the LLM didn't fill it.
    """
    if element.mva is None or element.mva == 0:
        parsed = parse_mva_from_text(element.transmission_scope)
        if parsed:
            element.mva = parsed

    return element


# ── Master Post-Processing Pipeline ───────────────────────────────────


def post_process_elements(
    elements: list[TransmissionElement],
    doc_type: DocType,
) -> list[TransmissionElement]:
    """Apply all business logic rules to extracted elements.

    This is the single entry point called after LLM extraction.
    Order matters:
    1. Inherit scheme names to children (before anything else)
    2. For each element:
       a. Generate unique element code
       b. Extract state/region for inter_intra
       c. Force correct status from doc_type
       d. Force correct source from doc_type
       e. Backfill MVA from scope text
       f. Normalise percentage fields

    Args:
        elements: Raw elements from the Pydantic AI Agent.
        doc_type: Document type for status/source rules.

    Returns:
        Post-processed elements with all business rules applied.
    """
    if not elements:
        return elements

    # Step 1: Parent-child scheme inheritance
    elements = inherit_scheme_to_children(elements)

    status = get_status_for_doc_type(doc_type)
    source = get_source_for_doc_type(doc_type)

    for i, elem in enumerate(elements, 1):
        # Step 2a: Unique element code
        elem.element_code = generate_element_code(elem, i, doc_type)

        # Step 2b: Extract state name for inter_intra_tx_element
        if not elem.inter_intra_tx_element or elem.inter_intra_tx_element.strip() == "":
            state = extract_state_name(
                elem.transmission_scheme, elem.transmission_scope
            )
            if state:
                elem.inter_intra_tx_element = state

        # Step 2c: Override status from doc_type (deterministic)
        elem.status = status

        # Step 2d: Override source from doc_type (deterministic)
        elem.source = source

        # Step 2e: Backfill MVA from scope
        elem = backfill_mva(elem)

        # Step 2f: Normalise percentages
        elem = normalise_percentages(elem)

    print(f"[business_logic] Post-processed {len(elements)} elements")
    print(f"[business_logic]   Status: {status}")
    print(f"[business_logic]   Source: {source}")

    # Stats
    with_mva = sum(1 for e in elements if e.mva and e.mva > 0)
    with_state = sum(1 for e in elements if e.inter_intra_tx_element)
    print(f"[business_logic]   Elements with MVA: {with_mva}/{len(elements)}")
    print(f"[business_logic]   Elements with state/region: {with_state}/{len(elements)}")

    return elements
